type Student {
  id: Int!
  name: String!
  sex: Boolean!
  age: Int
}

type Teacher {
  id: Int!
  name: String!
  subject: [String]!
  students: [Student]!
}

type Query {
  students: [Student]!
  studentById(id: Int!): Student
  teachers: [Teacher]!
}

type DelStudentRes {
  id: Int!
  success: Boolean!
}

input CreateStudentInput {
  name: String!
  sex: Boolean!
  age: Int
}

type Mutation {
  addStudent(createInput: CreateStudentInput): Student!
  updateStudent(id: Int!, name: String, sex: Boolean, age: Int): Student
  delStudent(id: Int!): DelStudentRes!
}
